apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::982248023155:user/github-deployer
      username: github-deployer
      groups:
        - system:masters
